#!/usr/bin/env bash
# 
# Install and configure HAproxy on your lb-01 server
#

sudo apt update

# Add HAProxy PPA
sudo apt install -y software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-1.8 -y
sudo apt update

sudo apt install -y haproxy=1.8.\*

haproxy_file="/etc/haproxy/haproxy.cfg"

# Configure Load Balancer
front_name="frontend http"
front_bind="bind *:80"
front_mode="mode http"
front_default="default_backend web-backend"
front_end="$front_name\n\t$front_bind\n\t$front_mode\n\t$front_default\n"

back_name="backend web-backend"
back_balance="balance roundrobin"
back_server1="server web1 52.87.230.189:80 check"
back_server2="server web2 18.234.80.136:80 check"
back_end="$back_name\n\t$back_balance\n\t$back_server1\n\t$back_server2"

sudo sed -i "$ a $front_end" $haproxy_file
sudo sed -i "$ a $back_end" $haproxy_file

# Restart HAProxy
sudo service haproxy restart
