#!/usr/bin/env bash
# Displays "Best School" 10 times
# Displays Same with Hi on a new line for the 9th iteration
i=1

while [ $i -lt "10" ]
do
	echo "Best School"

	if [ $i -eq "9" ]
	then
		echo "Hi"
		echo "Best School"
	fi

	((i += 1))
done
