#!/usr/bin/env bash
# Run nginx as the nginx user

# Kill all Apache processes
pkill apache2

# If a process is listening on port 80, change to port 8080
if grep -q "listen 80" /etc/nginx/sites-available/default ; then
    sed -i "s/listen 80/listen 8080/" /etc/nginx/sites-available/default
fi

# If a process is listening on port 80, change to port 8080
if grep -q "listen \[::\]:80" /etc/nginx/sites-available/default ; then
    sed -i "s/listen \[::\]:80/listen \[::\]:8080/" /etc/nginx/sites-available/default
fi

# Update Nginx config file owner and group
chown nginx:nginx /etc/nginx/nginx.conf

# Update Nginx config file permissions
chmod 0644 /etc/nginx/nginx.conf

# Start the nginx service as user nginx
su nginx -c "service nginx start"
